version: "3" # specify docker-compose version

# Define the services/containers to be run
services:
  nodejs-server-1:
    build:
      context: ./api
      dockerfile: debug.dockerfile
    ports:
      - "3000:3000"
    container_name: node-api-1
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    depends_on:
      - mongo

  nodejs-server-2:
    build:
      context: ./api
      dockerfile: debug.dockerfile
    ports:
      - "3001:3000"
    container_name: node-api-2
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    depends_on:
      - mongo

  nodejs-server-3:
    build:
      context: ./api
      dockerfile: debug.dockerfile
    ports:
      - "3002:3000"
    container_name: node-api-3
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    depends_on:
      - mongo

  angular-ui:
    build:
      context: ./app-ui
      dockerfile: debug.dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
      - ./app-ui:/usr/src/app/app-ui
      - /usr/src/app/app-ui/node_modules

  mongo: # name of the third service
    image: mongo # specify image to build container from
    container_name: mongo
    volumes:
      - ./mongo:/home/mongodb
    ports:
      - "27017:27017"
