version: '3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 42181:2181

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  mongo:
    # name of the third service
    image: mongo # specify image to build container from
    container_name: mongo
    volumes:
      - ./mongo:/home/mongodb
    ports:
      - "27017:27017"

  angular-ui:
    build:
      context: ./app-ui
      dockerfile: debug.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./app-ui:/usr/src/app/app-ui
      - /usr/src/app/app-ui/node_modules

  publisher:
    depends_on:
      - mongo
      - kafka-1
      - kafka-2
      - kafka-3
    build:
      context: ./publisher
    ports:
      - 3000:3000
  subscriber-1:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3001:3000

  subscriber-2:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3002:3000
  
  subscriber-3:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3003:3000

  subscriber-4:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3004:3000
  
  subscriber-5:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3005:3000

  subscriber-6:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3006:3000

  subscriber-7:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3007:3000

  subscriber-8:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3008:3000

  subscriber-9:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 3009:3000

  subscriber-10:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - publisher
      - mongo
    build:
      context: ./subscriber
    ports:
      - 30010:3000